#ifndef INTERFACES_HPP
#define INTERFACES_HPP

# include <string>
# include <unordered_map>
# include <unordered_set>

using	interfaceType		= std::string;
using	interfacVersions 	= std::unordered_set<std::string>;

static	const std::unordered_map<interfaceType , interfacVersions>	interfacesMap
{
		{"ivphysicsdebugoverlay", { "VPhysicsDebugOverlay001"} },
		{"ibasefilesystem", { "VBaseFileSystem011"} },
		{"ishadowmgr", { "VEngineShadowMgr002"} },
		{"idatacache", { "VDataCache003"} },
		{"ivengineserver", { "VEngineServer023"} },
		{"itoolframeworkinternal", { "VTOOLFRAMEWORKVERSION002"} },
		{"ivmodelrender", { "VEngineModel016"} },
		{"ivdebugoverlay", { "VDebugOverlay003"} },
		{"ivprofexport", { "VProfExport001"} },
		{"imdlcache", { "MDLCache004"} },
		{"istudiodatacache", { "VStudioDataCache005"} },
		{"ivrenderview", { "VEngineRenderView014"} },
		{"ivengineclient", { "VEngineClient014"} },
		{"ivgui", { "VGUI_ivgui008"} },
		{"ivengineclient013", { "VEngineClient013"} },
		{"icvarquery", { "VCvarQuery001"} },
		{"iserverpluginhelpers", { "ISERVERPLUGINHELPERS001"} },
		{"idownloadsystem", { "DownloadSystem001"} },
		{"ienginesound", { "IEngineSoundClient003","IEngineSoundServer003"} },
		{"isourcevirtualreality", { "SourceVirtualReality001"} },
		{"inetworkstringtablecontainer", { "VEngineClientStringTable001","VEngineServerStringTable001"} },
		{"iscenefilecache", { "SceneFileCache002"} },
		{"ienginetool", { "VENGINETOOL003"} },
		{"ctooldictionary", { "VTOOLDICTIONARY002"} },
		{"imatchmaking", { "VENGINE_MATCHMAKING_VERSION001"} },
		{"iplayerinfomanager", { "PlayerInfoManager002"} },
		{"ienginetoolframework", { "VENGINETOOLFRAMEWORK003"} },
		{"ienginetrace", { "EngineTraceServer003","EngineTraceClient003"} },
		{"ienginereplay", { "EngineReplay001"} },
		{"iqueuedloader", { "QueuedLoaderVersion001","QueuedLoaderVersion004"} },
		{"iengineclientreplay", { "EngineClientReplay001"} },
		{"igameeventmanager2", { "GAMEEVENTSMANAGER002"} },
		{"iservergamedll008", { "ServerGameDLL008"} },
		{"igameeventmanager", { "GAMEEVENTSMANAGER001"} },
		{"ivmodelinfo003", { "VModelInfoServer003"} },
		{"ivmodelinfo", { "VModelInfoServer004"} },
		{"iserverchoreotools", { "VSERVERCHOREOTOOLS001"} },
		{"ivmodelinfoclient", { "VModelInfoClient006"} },
		{"iclientrendertargets", { "ClientRenderTargets001"} },
		{"iuniformrandomstream", { "VEngineRandom001"} },
		{"ireplaydemoplayer", { "ReplayDemoPlayer001"} },
		{"ispatialpartition", { "SpatialPartition001"} },
		{"istaticpropmgrclient", { "StaticPropMgrClient004"} },
		{"imaterialsystem", { "VMaterialSystem080","VMaterialSystem081"} },
		{"istaticpropmgrserver", { "StaticPropMgrServer002"} },
		{"igameserverdata", { "GameServerData001"} },
		{"iclienttools", { "VCLIENTTOOLS001"} },
		{"ireplaysystem", { "ReplaySystem001"} },
		{"ibaseclientdll", { "VClient017"} },
		{"iuploadgamestats", { "ServerUploadGameStats001"} },
		{"ieffects", { "IEffects001"} },
		{"iengineapi", { "VENGINE_LAUNCHER_API_VERSION004"} },
		{"ivengineserver021", { "VEngineServer021"} },
		{"ivengineserver022", { "VEngineServer022"} },
		{"ienginevgui", { "VEngineVGui001"} },
		{"icliententitylist", { "VClientEntityList003"} },
		{"ixboxsystem", { "XboxSystemInterface001"} },
		{"ip4", { "VP4002"} },
		{"icvar", { "VEngineCvar007","VEngineCvar004"} },
		{"ifilesystem", { "VFileSystem017","VFileSystem022"} },
		{"iservertools", { "VSERVERTOOLS003"} },
		{"iclientleafsystem", { "ClientLeafSystem002"} },
		{"ihltvdirector", { "HLTVDirector001"} },
		{"iclientvirtualreality", { "ClientVirtualReality001"} },
		{"iprediction", { "VClientPrediction001"} },
		{"isoundemittersystembase", { "VSoundEmitter003","VSoundEmitter002"} },
		{"ireplayfactory", { "IReplayFactory001"} },
		{"iclientreplay", { "ClientReplay001"} },
		{"icenterprint", { "VCENTERPRINT002"} },
		{"iservertools001", { "VSERVERTOOLS001"} },
		{"iservertools002", { "VSERVERTOOLS002"} },
		{"imaterialsystemstub", { "VMaterialSystemStub001"} },
		{"iserverreplay", { "ServerReplay001"} },
		{"iservergamedll", { "ServerGameDLL010"} },
		{"iserverplugincallbacks", { "ISERVERPLUGINCALLBACKS003"} },
		{"iservergameclients003", { "ServerGameClients003"} },
		{"isurface", { "VGUI_Surface031","VGUI_Surface030"} },
		{"iservergameclients", { "ServerGameClients004"} },
		{"iplayerinfomanager_v1", {"PlayerInfoManager001" } },
		{"ibotmanager", { "BotManager001"} },
		{"ipluginhelperscheck", { "PluginHelpersCheck001"} },
		{"igamemovement", { "GameMovement001"} },
		{"iparticlesystemquery", { "VParticleSystemQuery001"} },
		{"igameconsole", { "GameConsole004"} },
		{"igameui", { "GameUI011"} },
		{"ivguimoduleloader", { "VGuiModuleLoader003"} },
		{"igamecoordinator", { "GAMECOORDINATOR003"} },
		{"imdllib", { "VMDLLIB001"} },
		{"ihammer", { "Hammer001"} },
		{"iinputsystem", { "InputSystemVersion001"} },
		{"icolorcorrectionsystem", { "COLORCORRECTION_VERSION_1"} },
		{"materialsystem_config_t", { "VMaterialSystemConfig002"} },
		{"ivballoctracker", { "VBAllocTracker001"} },
		{"imaterialsystemhardwareconfig", { "MaterialSystemHardwareConfig013","MaterialSystemHardwareConfig012"} },
		{"ishaderapi", { "ShaderApi030"} },
		{"idebugtextureinfo", { "DebugTextureInfo001"} },
		{"ishaderdevice", { "ShaderDevice001"} },
		{"ishaderdevicemgr", { "ShaderDeviceMgr001"} },
		{"ishadershadow", { "ShaderShadow010"} },
		{"ishadersystem", { "ShaderSystem002"} },
		{"inetworksystem", { "NetworkSystemVersion001"} },
		{"iserverbrowser", { "ServerBrowser005"} },
		{"ivguimodule", {"VGuiModuleServerBrowser001" } },
		{"isoundsystem", { "SoundSystem001"} },
		{"istudiorender", { "VStudioRender026","VStudioRender025"} },
		{"itooldictionary", { "VTOOLDICTIONARY002"} },
		{"iadminserver", { "AdminServer002"} },
		{"ishaderutil", { "VShaderUtil001"} },
		{"isqlwrapperfactory", { "ISQLWRAPPER001"} },
		{"ivraddll", { "vraddll_1"} },
		{"ilaunchabledll", { "launchable_dll_1"} },
		{"ivtex", { "VTEX_003"} },
		{"iinput", { "VGUI_Input005"} },
		{"iinputinternal", { "VGUI_InputInternal001"} },
		{"ischememanager", { "VGUI_Scheme010"} },
		{"isystem", { "VGUI_System010"} },
		{"ivideosubsystem", { "IVideoSubSystem002"} },
		{"ivideoservices", { "IVideoServices002"} },
		{"iphysics", { "VPhysics031"} },
		{"iphysicscollision", { "VPhysicsCollision007"} },
		{"iphysicssurfaceprops", { "VPhysicsSurfaceProps001"} },
		{"iprocessutils", { "VProcessUtils002","VProcessUtils001"} }
};

#endif
